name: template_builder_x
description: A sample command-line application to generate template directories and files.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  args: ^2.2.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  template_builder_x:
    main: bin/template_builder_x.dart
